source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               fragment.xml,\
               lib/nb-javac-api-shaded-jdk-26-35.jar,\
               lib/nb-javac-shaded-jdk-26-35.jar,\
               lib/nnb-doclint-shaded-1.0-SNAPSHOT.jar
