source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               fragment.xml,\
               lib/nb-javac-api-shaded-26.27.jar,\
               lib/nb-javac-shaded-26.27.jar
